<?php
/**
 * Theme Writer — Securely write AI-generated theme files to disk.
 *
 * Handles file validation, directory creation, and safe writes to the
 * WordPress themes directory. Enforces extension whitelists, path traversal
 * protection, and proper file permissions.
 *
 * @package    WPVibe
 * @subpackage WPVibe/includes
 * @since      1.0.0
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class VB_Theme_Writer
 *
 * Responsible for securely writing theme files generated by the AI to the
 * WordPress themes directory. Validates all file paths, enforces an extension
 * whitelist, and manages theme directory lifecycle (create, write, delete).
 *
 * @since 1.0.0
 */
class VB_Theme_Writer {

	/**
	 * File extensions allowed for theme files.
	 *
	 * @since 1.0.0
	 * @var string[]
	 */
	const ALLOWED_EXTENSIONS = array(
		'php',
		'css',
		'js',
		'json',
		'svg',
		'png',
		'jpg',
		'html',
		'txt',
	);

	/**
	 * File permissions for written files.
	 *
	 * @since 1.0.0
	 * @var int
	 */
	const FILE_PERMISSIONS = 0644;

	/**
	 * Directory permissions for created directories.
	 *
	 * @since 1.0.0
	 * @var int
	 */
	const DIR_PERMISSIONS = 0755;

	/**
	 * Write theme files to the WordPress themes directory.
	 *
	 * Creates the theme directory if it does not exist, validates each file
	 * path, creates subdirectories as needed, and writes file contents. Errors
	 * are collected per-file but do not halt processing of remaining files.
	 *
	 * @since 1.0.0
	 *
	 * @param string $theme_slug The theme directory name (slug).
	 * @param array  $files      Array of file entries, each with `path` (string)
	 *                           and `content` (string) keys.
	 * @return array {
	 *     @type bool     $success   True if all files were written without error.
	 *     @type string   $theme_dir Absolute path to the theme directory.
	 *     @type string[] $errors    Array of error messages, one per failed file.
	 * }
	 */
	public function write_theme( string $theme_slug, array $files ): array {
		$errors    = array();
		$theme_root = get_theme_root();
		$theme_dir  = trailingslashit( $theme_root ) . $theme_slug;

		// Create theme directory if it does not exist.
		if ( ! is_dir( $theme_dir ) ) {
			if ( ! wp_mkdir_p( $theme_dir ) ) {
				return array(
					'success'   => false,
					'theme_dir' => $theme_dir,
					'errors'    => array( 'Failed to create theme directory: ' . $theme_dir ),
				);
			}
		}

		foreach ( $files as $file ) {
			$relative_path = $file['path'] ?? '';
			$content       = $file['content'] ?? '';

			// Validate the relative file path.
			if ( ! $this->validate_path( $relative_path ) ) {
				$errors[] = sprintf(
					'Invalid file path rejected: %s',
					sanitize_text_field( $relative_path )
				);
				continue;
			}

			$absolute_path = trailingslashit( $theme_dir ) . $relative_path;

			// Scan files for dangerous patterns.
			$ext = strtolower( pathinfo( $relative_path, PATHINFO_EXTENSION ) );

			// Scan PHP files for dangerous function calls and XSS.
			if ( 'php' === $ext ) {
				$dangerous = $this->scan_php_content( $content );
				if ( ! empty( $dangerous ) ) {
					// Auto-fix common XSS issues instead of blocking.
					$fixed_content = $this->auto_fix_php_security( $content );
					$recheck       = $this->scan_php_content( $fixed_content );
					if ( ! empty( $recheck ) ) {
						$errors[] = sprintf(
							'Blocked dangerous PHP in file: %s',
							sanitize_text_field( $relative_path )
						);
						VB_Logger::instance()->warning(
							'Blocked dangerous PHP patterns in AI-generated file: ' . sanitize_text_field( $relative_path )
						);
						continue;
					}
					$content = $fixed_content;
				}
			}

			// Scan JS files for dangerous patterns.
			if ( 'js' === $ext ) {
				$dangerous = $this->scan_js_content( $content );
				if ( ! empty( $dangerous ) ) {
					$errors[] = sprintf(
						'Blocked dangerous JavaScript in file: %s',
						sanitize_text_field( $relative_path )
					);
					VB_Logger::instance()->warning(
						'Blocked dangerous JS patterns in AI-generated file: ' . sanitize_text_field( $relative_path )
					);
					continue;
				}
			}

			// Verify the resolved path is still within the theme directory.
			$real_theme_dir = realpath( $theme_dir );

			if ( false === $real_theme_dir ) {
				$errors[] = sprintf(
					'Theme directory does not exist for file: %s',
					sanitize_text_field( $relative_path )
				);
				continue;
			}

			// Create subdirectories if needed.
			$file_dir = dirname( $absolute_path );

			if ( ! is_dir( $file_dir ) ) {
				if ( ! wp_mkdir_p( $file_dir ) ) {
					$errors[] = sprintf(
						'Failed to create directory for file: %s',
						sanitize_text_field( $relative_path )
					);
					continue;
				}
			}

			// After directory creation, verify the resolved path stays within the theme.
			$real_file_dir = realpath( $file_dir );

			if ( false === $real_file_dir || 0 !== strpos( $real_file_dir, $real_theme_dir ) ) {
				$errors[] = sprintf(
					'Path resolves outside theme directory: %s',
					sanitize_text_field( $relative_path )
				);
				continue;
			}

			// Build the final write path from the resolved directory to prevent
			// TOCTOU attacks (symlink created between validation and write).
			$safe_write_path = trailingslashit( $real_file_dir ) . basename( $relative_path );

			// Write file content with exclusive lock.
			$result = file_put_contents( $safe_write_path, $content, LOCK_EX );

			if ( false === $result ) {
				$errors[] = sprintf(
					'Failed to write file: %s',
					sanitize_text_field( $relative_path )
				);
				continue;
			}

			// Set file permissions.
			chmod( $safe_write_path, self::FILE_PERMISSIONS );
		}

		return array(
			'success'   => empty( $errors ),
			'theme_dir' => $theme_dir,
			'errors'    => $errors,
		);
	}

	/**
	 * Validate a relative file path for security.
	 *
	 * Checks for:
	 * - Null bytes
	 * - Absolute paths (leading `/` or Windows drive letters)
	 * - Directory traversal (`..`)
	 * - Hidden files (basename starting with `.`) except `.htaccess`
	 * - Extension whitelist
	 * - Maximum path length (255 characters)
	 * - Empty path
	 *
	 * @since 1.0.0
	 *
	 * @param string $path The relative file path to validate.
	 * @return bool True if the path is safe to write.
	 */
	private function validate_path( string $path ): bool {
		// No empty paths.
		if ( '' === $path || '' === trim( $path ) ) {
			return false;
		}

		// Max path length.
		if ( strlen( $path ) > 255 ) {
			return false;
		}

		// No null bytes.
		if ( false !== strpos( $path, "\0" ) ) {
			return false;
		}

		// Not absolute: no leading `/` or `\`.
		if ( '/' === $path[0] || '\\' === $path[0] ) {
			return false;
		}

		// Not absolute: no Windows drive letter (e.g., `C:` or `D:\`).
		if ( preg_match( '/^[A-Za-z]:/', $path ) ) {
			return false;
		}

		// No directory traversal.
		$normalized = str_replace( '\\', '/', $path );

		if ( false !== strpos( $normalized, '..' ) ) {
			return false;
		}

		// No hidden files (basename starting with `.`) except `.htaccess`.
		$basename = basename( $normalized );

		if ( '.' === $basename[0] && '.htaccess' !== $basename ) {
			return false;
		}

		// Check hidden directories in the path segments.
		$segments = explode( '/', $normalized );

		foreach ( $segments as $segment ) {
			if ( '' === $segment ) {
				continue;
			}

			// Directory segments must not start with `.`.
			if ( '.' === $segment[0] && $segment !== $basename ) {
				return false;
			}
		}

		// Extension must be in the allowed list.
		$extension = strtolower( pathinfo( $basename, PATHINFO_EXTENSION ) );

		if ( '' === $extension || ! in_array( $extension, self::ALLOWED_EXTENSIONS, true ) ) {
			return false;
		}

		return true;
	}

	/**
	 * Dangerous PHP function patterns that should never appear in AI-generated themes.
	 *
	 * Categories:
	 * - OS command execution
	 * - Code evaluation / dynamic execution
	 * - Direct superglobal access (must use WP sanitization functions)
	 * - Arbitrary file operations with variable paths
	 * - Network operations
	 * - XSS-prone patterns (unescaped output)
	 * - Obfuscation techniques
	 *
	 * @since 1.0.0
	 * @var string[]
	 */
	private const DANGEROUS_PHP_PATTERNS = array(
		// OS command execution.
		'/\b(passthru|shell_exec|popen|proc_open|pcntl_exec|dl)\s*\(/i',
		// Direct superglobal access — must use WP sanitization.
		'/\$_(GET|POST|REQUEST|COOKIE|SERVER)\s*\[/',
		// Arbitrary file operations with variable paths.
		'/\bfile_(get_contents|put_contents)\s*\(\s*\$/',
		'/\b(move_uploaded_file|copy)\s*\(\s*\$/',
		// Network operations.
		'/\b(curl_init|fsockopen|stream_socket_client)\s*\(/i',
		// Deprecated / dangerous evaluation patterns.
		'/\bcreate_function\s*\(/i',
		'/\bcall_user_func(_array)?\s*\(\s*\$/',
		'/\bpreg_replace\s*\(\s*[\'"]\/.*\/e\b/',
		// Obfuscation / encoding tricks.
		'/\b(base64_decode|str_rot13|gzinflate|gzuncompress)\s*\(\s*[\'\"]/i',
		'/\b(chr\s*\(\s*\d+\s*\)\s*\.?\s*){4,}/i',
		// extract() on untrusted data — variable injection risk.
		'/\bextract\s*\(/i',
		// Unescaped echo of WP dynamic data (XSS).
		'/\becho\s+(?!esc_html|esc_attr|esc_url|esc_textarea|wp_kses|tag_escape|wp_json_encode|__\(|_e\(|esc_html__|esc_attr__|esc_html_e|esc_attr_e|wp_nonce_field|wp_head|wp_footer|wp_body_open|get_header|get_footer|get_sidebar|get_template_part|do_action|the_|bloginfo|language_attr|body_class|post_class|comment_class|wp_list_comments|wp_link_pages|wp_nav_menu|wp_loginout|wp_register|dynamic_sidebar|get_search_form|comments_template|next_posts_link|previous_posts_link|paginate_links|\'|\"|\d|PHP_EOL|__DIR__|ABSPATH|TEMPLATEPATH)/',
	);

	/**
	 * Scan PHP file content for dangerous function calls.
	 *
	 * Returns an array of matched patterns. Empty array means content is safe.
	 *
	 * @since 1.0.0
	 *
	 * @param string $content The PHP file content to scan.
	 * @return string[] Array of matched dangerous patterns found.
	 */
	public function scan_php_content( string $content ): array {
		$matches = array();

		foreach ( self::DANGEROUS_PHP_PATTERNS as $pattern ) {
			if ( preg_match( $pattern, $content ) ) {
				$matches[] = $pattern;
			}
		}

		return $matches;
	}

	/**
	 * Dangerous JavaScript patterns that should not appear in theme JS files.
	 *
	 * @since 1.0.0
	 * @var string[]
	 */
	private const DANGEROUS_JS_PATTERNS = array(
		// Fetching external scripts dynamically.
		'/\bnew\s+Function\s*\(/i',
		// Crypto mining, beacon, tracking.
		'/\b(CoinHive|coinhive|cryptonight)\b/i',
		// Exfiltration patterns — sending data to external URLs.
		'/\bfetch\s*\(\s*[\'\"](https?:)?\/\/(?!fonts\.googleapis|cdn\.jsdelivr|cdn\.tailwindcss|unpkg\.com|cdnjs\.cloudflare)/i',
		'/\bnew\s+XMLHttpRequest/i',
		// WebSocket to unknown hosts.
		'/\bnew\s+WebSocket\s*\(\s*[\'\"]/i',
	);

	/**
	 * Scan JavaScript content for dangerous patterns.
	 *
	 * @since 1.0.0
	 *
	 * @param string $content JavaScript file content to scan.
	 * @return string[] Matched dangerous patterns.
	 */
	public function scan_js_content( string $content ): array {
		$matches = array();

		foreach ( self::DANGEROUS_JS_PATTERNS as $pattern ) {
			if ( preg_match( $pattern, $content ) ) {
				$matches[] = $pattern;
			}
		}

		return $matches;
	}

	/**
	 * Auto-fix common security issues in AI-generated PHP code.
	 *
	 * Attempts to wrap unescaped output in appropriate WP escaping functions.
	 * This is a best-effort fix — files that still fail scanning after this
	 * step are rejected entirely.
	 *
	 * @since 1.0.0
	 *
	 * @param string $content PHP file content.
	 * @return string Fixed content.
	 */
	private function auto_fix_php_security( string $content ): string {
		// Replace direct superglobal access with sanitized versions.
		$content = preg_replace(
			'/\$_GET\s*\[\s*[\'"](\w+)[\'"]\s*\]/',
			'sanitize_text_field( wp_unslash( $_GET[\'$1\'] ?? \'\' ) )',
			$content
		);
		$content = preg_replace(
			'/\$_POST\s*\[\s*[\'"](\w+)[\'"]\s*\]/',
			'sanitize_text_field( wp_unslash( $_POST[\'$1\'] ?? \'\' ) )',
			$content
		);
		$content = preg_replace(
			'/\$_REQUEST\s*\[\s*[\'"](\w+)[\'"]\s*\]/',
			'sanitize_text_field( wp_unslash( $_REQUEST[\'$1\'] ?? \'\' ) )',
			$content
		);

		return $content;
	}

	/**
	 * Generate a theme slug from a session ID and optional session name.
	 *
	 * If a non-empty session name is provided, it is sanitized and appended
	 * with the session ID. Otherwise a default slug is generated.
	 *
	 * @since 1.0.0
	 *
	 * @param int    $session_id   The chat session ID.
	 * @param string $session_name Optional human-readable session name.
	 * @return string The generated theme slug.
	 */
	public static function generate_slug( int $session_id, string $session_name = '' ): string {
		$session_name = trim( $session_name );

		if ( '' !== $session_name ) {
			$slug = sanitize_title( $session_name );

			// sanitize_title may return empty for non-latin input.
			if ( '' !== $slug ) {
				return $slug . '-' . $session_id;
			}
		}

		return 'wpvibe-' . $session_id;
	}

	/**
	 * Delete a theme directory and all its contents.
	 *
	 * Validates the slug to prevent path traversal, then recursively deletes
	 * the theme directory from the WordPress themes root.
	 *
	 * @since 1.0.0
	 *
	 * @param string $theme_slug The theme directory name (slug) to delete.
	 * @return bool True if the directory was successfully deleted or did not exist.
	 */
	public function delete_theme( string $theme_slug ): bool {
		// Validate slug: must not be empty.
		if ( '' === $theme_slug || '' === trim( $theme_slug ) ) {
			return false;
		}

		// Must not contain path separators or traversal sequences.
		if ( false !== strpos( $theme_slug, '/' ) || false !== strpos( $theme_slug, '\\' ) ) {
			return false;
		}

		if ( false !== strpos( $theme_slug, '..' ) ) {
			return false;
		}

		$theme_root = get_theme_root();
		$theme_dir  = trailingslashit( $theme_root ) . $theme_slug;

		// If it does not exist, consider it a success.
		if ( ! is_dir( $theme_dir ) ) {
			return true;
		}

		// Verify the directory is actually inside the themes root.
		$real_root = realpath( $theme_root );
		$real_dir  = realpath( $theme_dir );

		if ( false === $real_root || false === $real_dir ) {
			return false;
		}

		if ( 0 !== strpos( $real_dir, $real_root ) ) {
			return false;
		}

		return $this->recursive_delete( $real_dir );
	}

	/**
	 * Recursively delete a directory and all its contents.
	 *
	 * @since 1.0.0
	 *
	 * @param string $dir Absolute path to the directory to delete.
	 * @return bool True if the directory was successfully deleted.
	 */
	private function recursive_delete( string $dir ): bool {
		if ( ! is_dir( $dir ) ) {
			return false;
		}

		$items = scandir( $dir );

		if ( false === $items ) {
			return false;
		}

		foreach ( $items as $item ) {
			if ( '.' === $item || '..' === $item ) {
				continue;
			}

			$path = trailingslashit( $dir ) . $item;

			if ( is_dir( $path ) ) {
				if ( ! $this->recursive_delete( $path ) ) {
					return false;
				}
			} else {
				if ( ! unlink( $path ) ) {
					return false;
				}
			}
		}

		return rmdir( $dir );
	}
}
